### ISSUE TITLE
create module: Panic parsing module repository info

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#1477]
**Description**

Create module adds `sources` metadata based either from the kubebuilder `PROJECT` file or (if the input folder is a git repository) from the `.git` folder.

The parsing only works for kubebuilder projects and panics otherwise.

**Expected result**

Metadata is correctly extracted from the .git folder if the module is not a kubebuilder project.

**Actual result**

```
/ Creating module archive at "./mod"panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/kyma-project/cli/pkg/module/git.domain(0xc000c12cf0)
	/home/prow/go/src/github.com/kyma-project/cli/pkg/module/git/source.go:71 +0xa5
github.com/kyma-project/cli/pkg/module/git.Source({0xc000052044, 0x2e}, {0x0, 0x0}, {0x7ff7bfeff9e4, 0x5})
	/home/prow/go/src/github.com/kyma-project/cli/pkg/module/git/source.go:37 +0x205
github.com/kyma-project/cli/pkg/module.addSources(0xc0003a1c70, 0x5a0ad30?)
	/home/prow/go/src/github.com/kyma-project/cli/pkg/module/build.go:117 +0x56
github.com/kyma-project/cli/pkg/module.Build({0x40abdd0, 0x5a0ad30}, 0xc000effc80)
	/home/prow/go/src/github.com/kyma-project/cli/pkg/module/build.go:82 +0x2d4
github.com/kyma-project/cli/cmd/kyma/alpha/create/module.(*command).Run(0xc00059dbf0, {0x0?, 0x0?, 0x0?})
	/home/prow/go/src/github.com/kyma-project/cli/cmd/kyma/alpha/create/module/module.go:117 +0x3d0
github.com/kyma-project/cli/cmd/kyma/alpha/create/module.NewCmd.func1(0xc000de7b00?, {0xc000dcc960?, 0x6?, 0x6?})
	/home/prow/go/src/github.com/kyma-project/cli/cmd/kyma/alpha/create/module/module.go:54 +0x25
github.com/spf13/cobra.(*Command).execute(0xc000de7b00, {0xc000dcc900, 0x6, 0x6})
	/home/prow/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000dca000)
	/home/prow/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prow/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/home/prow/go/src/github.com/kyma-project/cli/cmd/main.go:13 +0x57
```
**Steps to reproduce**

Run the `kyma alpha create module` command on a non-kubebuilder project folder.

**Comment by pbochynski** [comment]
I think also the git repository is mandatory. If you run the command from a folder that is not in git it also doesn't work. Please provide an example of how to generate a module template having just YAML file with deployment (simple case).
