### ISSUE TITLE
Module template creation - [controller-runtime] log.SetLogger(...) was never called, logs will not be displayed

### ISSUE THREAD

**Issue by the1bit** [kyma-project/cli#1763]
**Description**

When I run the module creation command with Kyma-Cli I am facing the following warning. The command runs fine and the result is fine. 

**Version**: I used the unstable version which was available at 2023-09-07 16:27:09 CEST.
**OS**: Ubuntu 22.04 - Azure Pipeline

**Expected result**

```bash
- Module built
- Default CR validation succeeded
- Module archive created
- Adding layers to archive...
- Security scanning configured
- Module successfully pushed to "**********************"
- Template successfully generated at moduletemplate.yaml
```

**Actual result**

```bash
- Module built
[controller-runtime] log.SetLogger(...) was never called, logs will not be displayed:
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/log/log.go:59 +0xcd
sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0xc0008bc040, 0xc000b9f280?)
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/log/deleg.go:111 +0x32
github.com/go-logr/logr.Logger.Enabled(...)
	/home/prow/go/pkg/mod/github.com/go-logr/logr@v1.2.4/logr.go:261
github.com/go-logr/logr.Logger.Info({{0x3a993e8?, 0xc0008bc040?}, 0xc0000881c9?}, {0x3534809, 0x16}, {0x0, 0x0, 0x0})
	/home/prow/go/pkg/mod/github.com/go-logr/logr@v1.2.4/logr.go:274 +0x72
sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).Start(0xc0002f8780)
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/envtest/server.go:260 +0x419
github.com/kyma-project/cli/internal/envtest.(*Runner).Start(0xc0008860c0, {0xc000755290, 0x25}, 0xc000b9f788?)
	/home/prow/go/src/github.com/kyma-project/cli/internal/envtest/envtest.go:37 +0xfc
github.com/kyma-project/cli/pkg/module.runTestEnv({0x3a90f58, 0x57e9a60}, 0xc000730098, {0xc000755290, 0x25}, 0x43?)
	/home/prow/go/src/github.com/kyma-project/cli/pkg/module/validation.go:83 +0x125
github.com/kyma-project/cli/pkg/module.(*SingleManifestFileCRValidator).Run(0xc0002083c0, {0x3a90f58, 0x57e9a60}, 0xc000730098)
	/home/prow/go/src/github.com/kyma-project/cli/pkg/module/validation.go:413 +0x3eb
github.com/kyma-project/cli/cmd/kyma/alpha/create/module.(*command).validateDefaultCR(0xc0007f3470, {0x3a90f58, 0x57e9a60}, 0xc000c4bc70, 0x7fc0b53db108?)
	/home/prow/go/src/github.com/kyma-project/cli/cmd/kyma/alpha/create/module/module.go:410 +0x28a
github.com/kyma-project/cli/cmd/kyma/alpha/create/module.(*command).Run(0xc0007f3470, {0x3a90f58, 0x57e9a60})
	/home/prow/go/src/github.com/kyma-project/cli/cmd/kyma/alpha/create/module/module.go:263 +0x377
github.com/kyma-project/cli/cmd/kyma/alpha/create/module.NewCmd.func1(0xc00046e500?, {0x34f7004?, 0x4?, 0x34f70ec?})
	/home/prow/go/src/github.com/kyma-project/cli/cmd/kyma/alpha/create/module/module.go:107 +0x28
github.com/spf13/cobra.(*Command).execute(0xc00098bb00, {0xc0009981a0, 0xd, 0xd})
	/home/prow/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000804000)
	/home/prow/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(0xc000159720?)
	/home/prow/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x13
main.main()
	/home/prow/go/src/github.com/kyma-project/cli/cmd/main.go:13 +0x70
- Default CR validation succeeded
- Module archive created
- Adding layers to archive...
- Security scanning configured
- Module successfully pushed to "**********************"
- Template successfully generated at moduletemplate.yaml
```

**Steps to reproduce**

Command:
```bash
kyma alpha create module \
    --module-config-file ./modules/module-config.yaml \
    --path ./keda-manager \
    --registry "*********" \
    --sec-scanners-config ./keda-manager/sec.yaml \
     --module-archive-version-overwrite \
     --output=moduletemplate.yaml \
     --registry-cred-selector=******** \
      --credentials oauth2accesstoken:*******
```

**Troubleshooting**

**Comment by jeremyharisch** [comment]
Blocked by https://github.com/kyma-project/cli/issues/1846

**Comment by nesmabadr** [comment]
This was fixed by the removal of the module CR validation step from the module creation command
