### ISSUE TITLE
JUnit report crashes at nil, while fetching test reports.

### ISSUE THREAD

**Issue by dbadura** [kyma-project/cli#349]
**Description**
When cluster test suite is executed in prow and one of the test timeouts, CLI panic while generating junit report.

**Expected result**
CLI doesn't panic.

**Actual result**
CLI Panic at nil value.

Short logs:
```
Waiting for test suite to finish: 16 out of 22 test(s) have finished (Succeeded: 16, Failed: 0, Skipped: 0)...
X Waiting for test suite to finish
Error: timed out waiting for the condition
[7m2020/01/14 12:06:16 UTC [INFO] - Test summary[0m
Name:		testsuite-all
Concurrency:	5
MaxRetries:	1
StartTime:	2020-01-14 11:06:16 +0000 UTC
EndTime:	Not finished yet
Condition:	Running
Completed:	16/22
  TEST                         STATUS           RETRIED  NAMESPACE         POD                                                 
  compass-director             Running          No       compass-system    oct-tp-testsuite-all-compass-director-0             
  compass-e2e                  Running          No       kyma-system       oct-tp-testsuite-all-compass-e2e-0                  
  core-apiserver-proxy         Succeeded        No       kyma-system       oct-tp-testsuite-all-core-apiserver-proxy-0         
  dex-integration              Succeeded        No       kyma-system       oct-tp-testsuite-all-dex-integration-0              
  service-catalog              Succeeded        No       kyma-system       oct-tp-testsuite-all-service-catalog-0              
  dex-connection               Succeeded        No       kyma-system       oct-tp-testsuite-all-dex-connection-0               
  compass-provisioner-tests    NotYetScheduled  No       compass-system                                                        
  connector-tests              NotYetScheduled  No       compass-system                                                        
  knative-serving              Succeeded        No       knative-serving   oct-tp-testsuite-all-knative-serving-0              
  connector-service            Succeeded        No       kyma-integration  oct-tp-testsuite-all-connector-service-0            
  api-gateway                  Succeeded        No       kyma-system       oct-tp-testsuite-all-api-gateway-0                  
  compass-runtime-agent-tests  Succeeded        No       compass-system    oct-tp-testsuite-all-compass-runtime-agent-tests-0  
  kiali                        Succeeded        No       kyma-system       oct-tp-testsuite-all-kiali-0                        
  monitoring                   Succeeded        No       kyma-system       oct-tp-testsuite-all-monitoring-0                   
  rafter                       NotYetScheduled  No       kyma-system                                                           
  event-bus                    Succeeded        No       kyma-system       oct-tp-testsuite-all-event-bus-0                    
  logging                      Succeeded        No       kyma-system       oct-tp-testsuite-all-logging-0                      
  connection-token-handler     Succeeded        No       kyma-integration  oct-tp-testsuite-all-connection-token-handler-0     
  core-api-controller          Succeeded        No       kyma-system       oct-tp-testsuite-all-core-api-controller-0          
  core-cluster-users           Succeeded        No       kyma-system       oct-tp-testsuite-all-core-cluster-users-0           
  core-kubeless                Succeeded        No       kyma-system       oct-tp-testsuite-all-core-kubeless-0                
  e2e-kubeless                 NotYetScheduled  No       kyma-system                                                           
[7m2020/01/14 12:06:17 UTC [INFO] - Fetching logs due to test suite failure[0m
- Fetching logs from testing pods in Failed status...
Fetching logs
  No logs to fetch for testing pods in status "Failed"
- Fetching logs from testing pods in Unknown status...
Fetching logs
  No logs to fetch for testing pods in status "Unknown"
- Fetching logs from testing pods in Running status due to running afer test suite timeout...
Fetching logs
X Fetching logs
Error: while fetching logs: while fetching logs for pod "oct-tp-testsuite-all-compass-director-0": the server rejected our request for an unknown reason (get pods oct-tp-testsuite-all-compass-director-0)
[7m2020/01/14 12:06:17 UTC [INFO] - Generate JUnit test summary[0m
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d81bdc]

goroutine 1 [running]:
github.com/kyma-project/cli/internal/junitxml.(*Creator).newRunningJUnitTestCase(0xc0006878a0, 0xc0003a1150, 0x10, 0xc0003a1160, 0xe, 0xc0003a1170, 0x7, 0xc00010dcc0, 0x1, 0x1, ...)
	/home/prow/go/src/github.com/kyma-project/cli/internal/junitxml/report.go:173 +0x1bc
github.com/kyma-project/cli/internal/junitxml.(*Creator).mapToTestCases(0xc0006878a0, 0xc0002ac000, 0x16, 0x20, 0xc0000fee00, 0x0, 0x0, 0x0, 0x0)
	/home/prow/go/src/github.com/kyma-project/cli/internal/junitxml/report.go:115 +0x19b
github.com/kyma-project/cli/internal/junitxml.(*Creator).generateReport(0xc0006878a0, 0xc0000fee00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0003d97f8, ...)
	/home/prow/go/src/github.com/kyma-project/cli/internal/junitxml/report.go:52 +0xad
github.com/kyma-project/cli/internal/junitxml.(*Creator).Write(0xc0006878a0, 0x27d18a0, 0xc00000e018, 0xc0000fee00, 0x0, 0xc00053aca0)
	/home/prow/go/src/github.com/kyma-project/cli/internal/junitxml/report.go:33 +0x4d
github.com/kyma-project/cli/cmd/kyma/test/status.(*command).printTestSuiteStatus(0xc0002c7a00, 0xc0000fee00, 0x7ffef1db2f32, 0x5, 0x0, 0x0)
	/home/prow/go/src/github.com/kyma-project/cli/cmd/kyma/test/status/cmd.go:119 +0x3ad
github.com/kyma-project/cli/cmd/kyma/test/status.(*command).Run(0xc0002c7a00, 0xc0002cc820, 0x1, 0x2, 0x0, 0x0)
	/home/prow/go/src/github.com/kyma-project/cli/cmd/kyma/test/status/cmd.go:64 +0x249
github.com/kyma-project/cli/cmd/kyma/test/status.NewCmd.func1(0xc000471180, 0xc0002cc820, 0x1, 0x2, 0x0, 0x0)
	/home/prow/go/src/github.com/kyma-project/cli/cmd/kyma/test/status/cmd.go:42 +0x48
github.com/spf13/cobra.(*Command).execute(0xc000471180, 0xc0002cc7a0, 0x2, 0x2, 0xc000471180, 0xc0002cc7a0)
	/home/prow/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002ea000, 0xc0002ea000, 0xc0003d9f88, 0xc000058178)
	/home/prow/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prow/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/home/prow/go/src/github.com/kyma-project/cli/cmd/main.go:13 +0x4b
[7m2020/01/14 12:06:17 UTC [INFO] All test pods should be terminated. Checking...[0m
```
Logs: https://status.build.kyma-project.io/log?id=1217033679595900930&job=pre-master-kyma-gke-compass-integration

**Steps to reproduce**
Try to force cluster test definition timeout, but it's only my guess.

**Troubleshooting**

**Comment by mszostok** [comment]
the problem is that the Octopus does not set`CompletionTime` when the test case is timed out or still running, so total time needs to be calc only if possible. I will provide a pr to fix that
