### ISSUE TITLE
version cmd: Panic when cluster kyma version can't be determined

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#435]
**Description**
The CLI `version` command panics when trying to get the Kyma version installed on a cluster and the installer image has no tag.

**Expected result**
The version command has a fallback in case the cluster kyma version can't be determined from the installer image tag, printing something like `N/A`.

**Actual result**
CLI panics:
```
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/kyma-project/cli/cmd/kyma/version.KymaVersion(0x0, 0x2d59ec0, 0xc0003a6e10, 0x0, 0xe, 0x1c, 0xc000082d80)
        /home/prow/go/src/github.com/kyma-project/cli/cmd/kyma/version/version.go:77 +0x1fc
github.com/kyma-project/cli/pkg/installation.(*Installation).buildResult(0xc00056c480, 0x0, 0x0, 0x0)
        /home/prow/go/src/github.com/kyma-project/cli/pkg/installation/installation.go:657 +0x62
github.com/kyma-project/cli/pkg/installation.(*Installation).InstallKyma(0xc00056c480, 0x0, 0x0, 0x0)
        /home/prow/go/src/github.com/kyma-project/cli/pkg/installation/installation.go:179 +0x68b
github.com/kyma-project/cli/cmd/kyma/install.(*command).Run(0xc000109a40, 0x0, 0x0)
        /home/prow/go/src/github.com/kyma-project/cli/cmd/kyma/install/cmd.go:134 +0x203
github.com/kyma-project/cli/cmd/kyma/install.NewCmd.func1(0xc0002dac80, 0xc0002764f0, 0x0, 0x1, 0x0, 0x0)
        /home/prow/go/src/github.com/kyma-project/cli/cmd/kyma/install/cmd.go:92 +0x31
github.com/spf13/cobra.(*Command).execute(0xc0002dac80, 0xc0002764d0, 0x1, 0x1, 0xc0002dac80, 0xc0002764d0)
        /home/prow/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x46c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000527180, 0xc000527180, 0xc0005adf88, 0xc0000521d8)
        /home/prow/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x303
github.com/spf13/cobra.(*Command).Execute(...)
        /home/prow/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /home/prow/go/src/github.com/kyma-project/cli/cmd/main.go:17 +0x57
```
**Steps to reproduce**
- Create a custom kyma installer image without a tag.
- Push the image to a docker registry.
- Use that image as installation source on the CLI install command: `kyma install -s <my-image>`
- After installation finishes, run `kyma version`

**Comment by suleymanakbas91** [comment]
With [this change](73737c63527aaf0f46f331eb25b3124e01e06bf6), we now check if `image` field has two fields (image:tag). If not, we print `N/A` that solves this bug.
