### ISSUE TITLE
kyma-cli 1.18.1 osx build failure with go1.15

### ISSUE THREAD

**Issue by chenrui333** [kyma-project/cli#733]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>test failure</summary>

```
==> /usr/local/Cellar/kyma-cli/1.18.1/bin/kyma install --kubeconfig ./kubeconfig 2>&1
runtime: netpoll: break fd ready for -2
fatal error: runtime: netpoll: break fd ready for something unexpected

runtime stack:
runtime.throw(0x3d98ca7, 0x39)
	runtime/panic.go:1116 +0x72
runtime.netpoll(0x12717bd6b, 0x9300a513f9c01)
	runtime/netpoll_kqueue.go:147 +0x33e
runtime.findrunnable(0xc000076800, 0x0)
	runtime/proc.go:2448 +0x785
runtime.schedule()
	runtime/proc.go:2683 +0x2d7
runtime.park_m(0xc000102480)
	runtime/proc.go:2851 +0x9d
runtime.mcall(0x80000)
	runtime/asm_amd64.s:318 +0x5b

goroutine 1 [runnable, locked to thread]:
golang.org/x/text/internal/language.init()
	golang.org/x/text@v0.3.3/internal/language/lookup.go:362 +0x13c

goroutine 4 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x5741600)
	k8s.io/klog@v1.0.0/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
	k8s.io/klog@v1.0.0/klog.go:411 +0xd8

goroutine 9 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x57416e0)
	k8s.io/klog/v2@v2.0.0/klog.go:1107 +0x8b
created by k8s.io/klog/v2.init.0
	k8s.io/klog/v2@v2.0.0/klog.go:416 +0xd8

goroutine 10 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000214c00)
	go.opencensus.io@v0.22.5/stats/view/worker.go:276 +0x105
created by go.opencensus.io/stats/view.init.0
	go.opencensus.io@v0.22.5/stats/view/worker.go:34 +0x68
Error: kyma-cli: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <1> expected but was
<2>.
```

</details>

Full build log is in here, https://github.com/Homebrew/homebrew-core/runs/1780001744
relates to https://github.com/Homebrew/homebrew-core/pull/69877

**Comment by suleymanakbas91** [comment]
Thanks for letting us know about the problem @chenrui333! We have tried to address the issue, but it is not trivial. Since it is only happening in case of using go v1.5 and running on MacOS 10.14, we decided not to spend so much time on it at the moment. Do you think it can be a blocker for the Homebrew formula at some point?

**Comment by a-thaler** [comment]
I will close the ticket. If you think we should do the investment to keep homebrew support please re-open it.
